#!/bin/bash

DOCKER_ID=$(docker build . 2>&1 | tail -n1 | grep 'Successfully built' | cut -d' ' -f3)
if [ "$DOCKER_ID" != "" ];
then
  docker ps | grep $DOCKER_ID >/dev/null
  if [ $? != 0 ];
  then
    docker run $DOCKER_ID
  fi
fi

